#### 기본함수

In [1]:
def greet():
    print("안녕하세요")

greet()

안녕하세요


In [3]:
def add(a, b):
    return a + b

result = add(3, 5)
print(result)

8


In [4]:
def greet(name="홍길동"):
    print(f"안녕하세요, {name}님!")

greet()
greet("준호")

안녕하세요, 홍길동님!
안녕하세요, 준호님!


In [5]:
def multiply(*args):
    result = 1
    for num in args:
        result *= num
    return result

print(multiply(2,3,4))

24


In [6]:
def check_number(num):
    """숫자가 양수, 음수, 또는 0인지 확인"""
    if num > 0:
        return "양수입니다."
    elif num < 0:
        return "음수입니다."
    else:
        return "0입니다."
    
# 호출 예제
print(check_number(5))
print(check_number(-2))
print(check_number(0))

양수입니다.
음수입니다.
0입니다.


In [12]:
def login_check(username, password):
    """ 사용자 이름과 비밀번호를 확인 """
    if username == "admin" and password == "1234":
        return "로그인 성공"
    else:
        return "로그인 실패"
    
print(login_check("admin", "1234"))
print(login_check("admin", "5678"))

로그인 성공
로그인 실패


In [7]:
def find_max(numbers):
    max_num = numbers[0]
    for num in numbers:
        if num > max_num:
            max_num = num
    return max_num

numbers = [1,5,3,9,2]
print(find_max(numbers))

9


In [ ]:
def get_even_numbers(start, end):
    even_nums = []
    for num in range(start, end+1):     # range(A,B)에서 B는 포함되지 않으니 +1 해야 함
        if num % 2 == 0:
            even_nums.append(num)
    return even_nums

print(get_even_numbers(1, 10))

[2, 4, 6, 8, 10]


In [26]:
def saving_simulation(target_amount, montyly_saving):
    total = 0
    months = 0
    while total < target_amount:
        total += montyly_saving
        months += 1
        print(f"{months}개월 차: {total:,}")    # {total:,}에서 콤마는 숫자 1000단위 구분자 옵션
    return f"{months}개월 만에 목표 금액 달성"

print(saving_simulation(1000000, 200000), "\n")

## f"{total:,.2f}" : 천 단위 콤마 + 소수점 둘째 자리까지
total = 1234567.891
print(f"{total:,.2f}")

1개월 차: 200,000
2개월 차: 400,000
3개월 차: 600,000
4개월 차: 800,000
5개월 차: 1,000,000
5개월 만에 목표 금액 달성 

1,234,567.89


In [34]:
def guess_number(answer):
    count = 0
    guess = None
    
    while guess != answer:
        guess = int(input("1부터 100 사이의 숫자를 맞춰보세요: "))
        count += 1
        if guess < answer:
            print("더 큰 숫자입니다! :", guess)
        elif guess > answer:
            print("더 작은 숫자입니다! :", guess)
    return f"{guess} 정답입니다! {count}번 만에 맞추셨습니다."

print (guess_number(45))

45 정답입니다! 1번 만에 맞추셨습니다.


In [15]:
def normalize_data(numbers):
    """
    데이터를 0~1 사이의 값으로 정규화하는 함수
    정규화 = (값 - 최소값) / (최대값 - 최소값)
    매개변수:
        numbers: 정규화할 숫자 리스트
    반환값:
        정규화된 데이터 리스트(0~1 사이의 값)
    """
    
    min_value = min(numbers)
    max_value = max(numbers)
    normalized = []     # 정규화된 값을 저장할 리스트
    
    for num in numbers:
        norm_value = (num - min_value) / (max_value - min_value)
        normalized.append(norm_value)
    return normalized

data = [10, 20, 30, 40, 50]
print("===== 데이터 정규화 예제 =====")
print("원본데이터 :", data)
normalized = normalize_data(data)
print("정규화된 데이터 :", normalized)

===== 데이터 정규화 예제 =====
원본데이터 : [10, 20, 30, 40, 50]
정규화된 데이터 : [0.0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
def split_data(data, train_ratio = 0.8):
    """
    데이터를 학습용과 테스트용으로 분리하는 함수

    매개변수:
        data: 분할할 데이터 리스트
        train_ratio: 학습 데이터의 비율(기본값 0.8 = 80%)
    반환값:
        train_data: 학습용 데이터
        test_data: 테스트용 데이터
    """
    
    # 학습 데이터 개수 계산
    split_index = int(len(data) * train_ratio)
    
    # 데이터 분할
    train_data = data[:split_index]  # 처음부터 split_index까지
    test_data = data[split_index:]   # split_index부터 끝까지
    
    return train_data, test_data

# 데이터 분할 함수 사용 예시
full_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("===== 데이터 분할 예제 =====")
print("전체 데이터:", full_data)

# 80:20으로 분할
train, test = split_data(full_data)
print("\n기본 비율(80%)로 분할:")
print("학습 데이터:", train)
print("테스트 데이터:", test)

# 70:30으로 분할
train2, test2 = split_data(full_data, train_ratio=0.7)
print("\n다른 비율(70%)로 분할")
print("학습 데이터:", train2)
print("테스트 데이터:", test2)

===== 데이터 분할 예제 =====
전체 데이터: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

기본 비율(80%)로 분할:
학습 데이터: [1, 2, 3, 4, 5, 6, 7, 8]
테스트 데이터: [9, 10]

다른 비율(70%)로 분할
학습 데이터: [1, 2, 3, 4, 5, 6, 7]
테스트 데이터: [8, 9, 10]


#### 람다함수

In [ ]:
multiply = lambda x, y : x * y
print(multiply(3,4))

12


In [2]:
square = lambda x : x ** 2
print(square(5))

25


In [3]:
add = lambda a, b : a + b
print(add(3,7))

10


In [5]:
check_even = lambda x : "짝수" if x % 2 == 0 else "홀수"
print(check_even(4))

짝수


In [ ]:
# sorted 사용 예제 : 새로운 매모리 주소 할당, 원본 보존
numbers = [5, 2, 9, 1]
sorted_numbers = sorted(numbers, key = lambda x : x)
print(sorted_numbers)

# sort 사용 예제
numbers.sort(key = lambda x : x)
print(numbers)

numbers.sort(reverse=True)
print(numbers)

numbers = [3, 1, 2]
result = numbers.sort()
print(result)
# None : sort()는 반환값이 없음

[1, 2, 5, 9]
[1, 2, 5, 9]
[9, 5, 2, 1]
None


### numpy

In [2]:
import numpy as np

# Numpy 벡터화 연산과 list 비교 예제
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]     # 리스트 컴프리헨션
print(new_list)

my_array = np.array([1, 2, 3])
new_array = my_array * 2                # 벡터화된 연산
print(new_array)

[2, 4, 6]
[2 4 6]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result)

[11 12 13 14 15]


In [4]:
arr = np.arange(0, 10, 2)       # arrange(start, stop, step)
                                # arange(5)는 0부터 시작하여 괄호 안 숫자 이전까지 [0,1,2,3,4]
print(arr)

[0 2 4 6 8]


In [5]:
arr = np.random.rand(3,3)       # 3행 3열 난수 : 0이상 1미만 사이의 난수 생성
print(arr)

[[0.28020327 0.52364394 0.55455085]
 [0.94266349 0.78528704 0.95447021]
 [0.79717821 0.92666463 0.07077076]]


In [6]:
arr = arr.reshape(1,9)
print(arr)

[[0.28020327 0.52364394 0.55455085 0.94266349 0.78528704 0.95447021
  0.79717821 0.92666463 0.07077076]]


In [7]:
npsum = np.sum([1,2,3])
print(npsum)

6


In [8]:
# 평균값
npmean = np.mean([1,2,3])       
print(npmean)

2.0


In [9]:
# 표준편차. 교재 예제 참조
np.std([175,117,179,181,183])

np.float64(25.13961017995307)

In [11]:
data = np.arange(1, 11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
sum_data = np.sum(data)
print("합:", sum_data)

합: 55


In [13]:
mean_data = np.mean(data)
print("평균:", mean_data)

평균: 5.5


In [14]:
std_data = np.std(data)
print("표준편차:", std_data)

표준편차: 2.8722813232690143


In [16]:
# 2차원 배열의 생성
data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 전체 요소의 합
sum_all = np.sum(data)
print("전체 요소의 합:", sum_all)

전체 요소의 합: 45


In [17]:
# axis=0 : 행 방향, 세로 방향 / axis=1 : 열 방향, 가로 방향
# 각 행의 합
row_sum = np.sum(data, axis=1)
print("각 행의 합:", row_sum)

#각 열의 합
col_sum = np.sum(data, axis=0)
print("각 열의 합:", col_sum)

각 행의 합: [ 6 15 24]
각 열의 합: [12 15 18]


In [18]:
# 전체 요소의 평균
mean_all = np.mean(data)
print("전체 요소의 평균:", mean_all)

전체 요소의 평균: 5.0


In [19]:
# 각 행의 평균
row_mean = np.mean(data, axis=1)
print("각 행의 평균:", row_mean)

각 행의 평균: [2. 5. 8.]


In [20]:
# 각 열의 평균
col_mean = np.mean(data, axis=0)
print("각 열의 평균:", col_mean)

각 열의 평균: [4. 5. 6.]


In [22]:
# 전체 요소의 표준편차
std_all = np.std(data)
print("전체 요소의 표준편차:", std_all)

전체 요소의 표준편차: 2.581988897471611


In [23]:
# 각 행의 표준편차
row_std = np.std(data, axis=1)
print("각 행의 표준편차:", row_std)

각 행의 표준편차: [0.81649658 0.81649658 0.81649658]


In [24]:
# 각 열의 표준편차
col_std = np.std(data, axis=0)
print("각 열의 표준편차:", col_std)

각 열의 표준편차: [2.44948974 2.44948974 2.44948974]


In [26]:
# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], 
                [4, 5, 6]])

# 배열의 shape 확인
print("arr1의 shape:", arr1.shape)
print("arr2의 shape:", arr2.shape)

arr1의 shape: (5,)
arr2의 shape: (2, 3)


In [27]:
# 특정 요소에 접근
print(arr2[1, 2])       # 2 번째 행, 세 번째 행

6


In [28]:
# 슬라이싱
print(arr2[:, 1])       # 모든 행의 두 번째 열

[2 5]


In [29]:
# 특정 요소에 접근
print(arr2[0][1])       # 첫 번째 행의 두 번째 요소(특정 위치의 값을 가져올 때)

2


### Pandas

In [ ]:
import pandas as pd